<?php
// link28 settings file
// Version: 1.4
// Created: 2026-06-27 16:49:11

$link1 = 'https://facebook.com';
$image1 = 'facebook.jpg';
$txt1 = 'Facebook';
$link2 = 'https://www.blitzortung.org/en/live_lightning_maps.php?map=30';
$image2 = 'blitzortung.png';
$txt2 = 'bliztorung';
$link3 = 'https://weather.gov';
$image3 = 'NWS.png';
$txt3 = 'weather gov';
$link4 = 'ui.com';
$image4 = 'ubiquity.jpg';
$txt4 = 'ui2';
$link5 = 'LCWO.net';
$image5 = 'lcwo.png';
$txt5 = 'LCWO';
$link6 = '';
$image6 = '../../f.jpg';
$txt6 = '';
$link7 = '';
$image7 = '../../f.jpg';
$txt7 = '';
$link8 = '';
$image8 = '../../f.jpg';
$txt8 = '';
$link9 = '';
$image9 = '../../f.jpg';
$txt9 = '';
$link10 = '';
$image10 = '../../f.jpg';
$txt10 = '';
$link11 = 'google.com';
$image11 = 'Nvr2.jpg';
$txt11 = 'elgoog';
$link12 = '';
$image12 = '../../f.jpg';
$txt12 = '';
$link13 = '';
$image13 = '../../f.jpg';
$txt13 = '';
$link14 = '';
$image14 = '../../f.jpg';
$txt14 = '';
$link15 = 'http://www.findu.com/cgi-bin/panel.cgi?call=FW0336&bgcolor=0,0,0&rcolor=0,255,0&acolor=0,0,255&fcolor=0,0,255&xsize=900';
$image15 = '../../cwop.jpg';
$txt15 = 'CWOP';
$link16 = '';
$image16 = '../../f.jpg';
$txt16 = '';
$link17 = 'http://www.weatherforyou.com/weather/pennsylvania/tower+city.html';
$image17 = 'http://www.weatherforyou.net/fcgi-bin/hw3/hw3.cgi?config=png&forecast=zandh&alt=hwizandh&place=tower+city&state=pa&country=us&daysonly=2&maxdays=5';
$txt17 = 'Latest Tower City, Pennsylvania, weather conditions and forecast';
$link18 = '';
$image18 = '../../f.jpg';
$txt18 = '';
$link19 = 'https://career4.successfactors.com/career?company=Hersheys&site';
$image19 = 'Hersheys.png';
$txt19 = 'Hershey jobs';
$link20 = '';
$image20 = '../../f.jpg';
$txt20 = '';
$link21 = '';
$image21 = '../../f.jpg';
$txt21 = '';
$link22 = '';
$image22 = '../../f.jpg';
$txt22 = '';
$link23 = '';
$image23 = '../../f.jpg';
$txt23 = '';
$link24 = '';
$image24 = '../../f.jpg';
$txt24 = '';
$link25 = '';
$image25 = '../../f.jpg';
$txt25 = '';
$link26 = '';
$image26 = '../../f.jpg';
$txt26 = '';
$link27 = '../../index.php';
$image27 = '../../Mainpage.jpg';
$txt27 = 'Mainpage';
$link28 = '../../settings/editor.php?pagename=shortcuts';
$image28 = 'Settings.png';
$txt28 = 'Settings';


